-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg1jxhPMwJ/q6alAbm
S+oacDZgmsS/hGCLN8p8RnH4U8SgCgYIKoZIzj0DAQehRANCAAQMxMeZP1QPcx4x
RqGhlHDVFsgK5OFnn3VzFt2ufWIxtX6yiQFI0Bt+P/YreR2BgnQBp/oDpqVi75k7
Az8wNNiU
-----END PRIVATE KEY-----